# Generated by Django 4.0.10 on 2023-03-07 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='qeustion',
            new_name='question',
        ),
    ]
